### PR TITLE
Generates random name

### PR DESCRIPTION
**Pull request by Daddyhughes111**
namePicker.py created which generates a random name and returns it.

### CODE REVIEW

**Comment by sk0g** [comment]
Hey, while that's a good starting point for the name picker, I wanted to go a bit more in depth, without getting too much into it. I'd like to pass the team city before generating a name, and having 6-7 groups of countries, so say Balkan, Latin, Scandinavian, British, etc. Take a few typical names and last names, as well as a % chance for any other name being present in the teams. It'd be higher for British teams, but very low for say, Balkan teams.

Are you interested in collaborating? I'm learning Python at the moment, and doing this for an excuse to code as of right now.

**Comment by Daddyhughes111** [comment]
Yeah sounds good! That was more of just a quick template starting point sort of thing. And yeah i'm learning python right now too and I'd love to collaborate :)

**Comment by sk0g** [comment]
Sweet, do you have Steam/ Discord or something of that sort? I don't think commit comments are meant for chatting!

**Comment by Daddyhughes111** [comment]
Yup both! discord: Daddyhughes111 #4758
steam: http://steamcommunity.com/id/ilovelaracroft/

**Comment by sk0g** [comment]
I've sent you a friend request on steam, I'll be on Steam soon enough. Closing this for now though.

**Pull request closed without merging**
